force-app/main/default/objects/Limit_Tracker__c/Limit_Tracker__c.object-meta.xml
<CustomObject>
    <description>Object to track limit consumption of a discrete piece of code.</description>
    <label>Limit Tracker</label>
    <nameField>
        <label>Limit Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limit Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/Limit_Tracker_Snapshot__c.object-meta.xml
<CustomObject>
    <description>Snapshot of the limits consumption of a tracked piece of code.</description>
    <label>Limit Tracker Snapshot</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Limit Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limit Tracker Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>Contains additional information to help diagnose a sudden increase in limits consumption.</description>
    <label>Additional Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/CPU__c.field-meta.xml
<CustomField>
    <fullName>CPU__c</fullName>
    <description>The CPU time consumed by the tracked code (in milliseconds)</description>
    <label>CPU</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/DML_Records__c.field-meta.xml
<CustomField>
    <fullName>DML_Records__c</fullName>
    <description>The number of DML records consumed by the tracked code.</description>
    <label>DML Records</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/DML_Statements__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements__c</fullName>
    <description>The number of DML statements consumed by the tracked code.</description>
    <label>DML Statements</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/Heap__c.field-meta.xml
<CustomField>
    <fullName>Heap__c</fullName>
    <description>The heap consumed by the tracked code in bytes.</description>
    <label>Heap</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/JSON_Additional_Info__c.field-meta.xml
<CustomField>
    <fullName>JSON_Additional_Info__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the additional information provided in JSON format for further processing?</description>
    <label>JSON Additional Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/Limit_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Limit_Tracker__c</fullName>
    <description>The parent limit tracker.</description>
    <label>Limit Tracker</label>
    <referenceTo>Limit_Tracker__c</referenceTo>
    <relationshipLabel>Limit Tracker Snapshots</relationshipLabel>
    <relationshipName>Limit_Tracker_Snapshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/SOQL_Queries__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Queries__c</fullName>
    <description>The number of SOQL queries consumed by the tracked code.</description>
    <label>SOQL Queries</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/SOQL_Records__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Records__c</fullName>
    <description>The number of SOQL records consumed by the tracked code.</description>
    <label>SOQL Records</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user executing the tracked code.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Limit_Tracker_Snapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LimitSnapshotServiceTest.cls
@isTest
private class LimitSnapshotServiceTest {
    @isTest
    static void TestGetAdditionalRecords()
    {
        Account acc=new Account(Name='Unit Test');
        insert acc;
        
        Limit_Tracker__c tracker=new Limit_Tracker__c(Name='Test Tracker');
        insert tracker;

        Limit_Tracker_Snapshot__c trackerSnapshot=
                                new Limit_Tracker_Snapshot__c();

        trackerSnapshot.CPU__c=1;
        trackerSnapshot.DML_Records__c=1;
        trackerSnapshot.DML_Statements__c=1;
        trackerSnapshot.Heap__c=1;
        trackerSnapshot.SOQL_Queries__c=1;
        trackerSnapshot.SOQL_Records__c=1;
        trackerSnapshot.JSON_Additional_Info__c=true;
        trackerSnapshot.Additional_Information__c=
                '{ "parentAccount": {' +
                '     "recordId":"' + acc.Id + '"' +
                '   }' +
                '}';

        trackerSnapshot.Limit_tracker__c=tracker.Id;    
        trackerSnapshot.User__c=UserInfo.getUserId();
        insert trackerSnapshot;

        LimitSnapshotServiceIF service = LimitSnapshotService.GetService();
        Test.startTest();
        List<AssociatedRecord> associatedRecords=
                    service.getAssociatedRecordsForSnapshot(trackerSnapshot.Id);
        Test.stopTest();
        Assert.areEqual(2, associatedRecords.size(), 
                       'Expected 2 associated records - account and user');
    }
}