force-app/main/default/objects/Limit_Alert_Notifier__mdt/Limit_Alert_Notifier__mdt.object-meta.xml
<CustomObject>
    <description>Configuration record for a limit alert notifier.</description>
    <label>Limit Alert Notifier</label>
    <pluralLabel>Limit Alert Notifiers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Limit_Alert_Notifier__mdt/fields/Additional_Config__c.field-meta.xml
<CustomField>
    <fullName>Additional_Config__c</fullName>
    <description>Additional configuration information. This will be passed verbatim to the configure method of the Apex class implementing the LimitNotifierInterface interface.</description>
    <label>Additional Config</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Limit_Alert_Notifier__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <description>The name of the Apex class that implements the AlertNotifierInterface interface.</description>
    <label>Apex Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Limit_Alert_Notifier__mdt/fields/Namespace__c.field-meta.xml
<CustomField>
    <fullName>Namespace__c</fullName>
    <description>The namespace that the Apex class is part of</description>
    <label>Namespace</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/Limit_Snapshot__e.object-meta.xml
<CustomObject>
    <description>Snapshot of key limit consumption by a discrete piece of code.</description>
    <label>Limit Snapshot</label>
    <pluralLabel>Limit Snapshots</pluralLabel>
</CustomObject>

force-app/main/default/objects/Limit_Snapshot__e/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>Contains additional information to help diagnose why this limit snapshot exhibits a considerable change from the previous one captured.</description>
    <label>Additional Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/CPU__c.field-meta.xml
<CustomField>
    <fullName>CPU__c</fullName>
    <description>The CPU consumed by the tracked code (in milliseconds)</description>
    <label>CPU</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/DML_Records__c.field-meta.xml
<CustomField>
    <fullName>DML_Records__c</fullName>
    <description>The number of DML records consumed by the tracked code.</description>
    <label>DML Records</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/DML_Statements__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements__c</fullName>
    <description>The number of DML statements consumed by the tracked code.</description>
    <label>DML Statements</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/Heap__c.field-meta.xml
<CustomField>
    <fullName>Heap__c</fullName>
    <description>The heap consumed by the tracked code in bytes.</description>
    <label>Heap</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>The unique name for the discrete piece of code for which limit consumption is captured - this does not need to be a method or class name, just the name that you refer to for that processing.</description>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/SOQL_Queries__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Queries__c</fullName>
    <description>The number of SOQL queries consumed by the tracked code.</description>
    <label>SOQL Queries</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/SOQL_Records__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Records__c</fullName>
    <description>The number of SOQL records consumed by the tracked code.</description>
    <label>SOQL Records</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <description>The record ID for the user executing the tracked code.</description>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker__c/Limit_Tracker__c.object-meta.xml
<CustomObject>
    <description>Object to track limit consumption of a discrete piece of code.</description>
    <label>Limit Tracker</label>
    <nameField>
        <label>Limit Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limit Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit_Tracker__c/fields/CPU_Alert_Change__c.field-meta.xml
<CustomField>
    <fullName>CPU_Alert_Change__c</fullName>
    <description>If the CPU consumption increases by this percentage between snapshots raise an alert.</description>
    <label>CPU Alert Change</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker__c/fields/CPU_Alert_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>CPU_Alert_Threshold_1__c</fullName>
    <description>Alert if the CPU consumption exceeds this threshold</description>
    <label>CPU Alert Threshold 1</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker__c/fields/CPU_Last__c.field-meta.xml
<CustomField>
    <fullName>CPU_Last__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The last CPU time recorded</description>
    <label>CPU Last</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker__c/fields/DML_Records_Last__c.field-meta.xml
<CustomField>
    <fullName>DML_Records_Last__c</fullName>
    <formula>Last_Snapshot__r.DML_Records__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DML Records Last</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker__c/fields/DML_Statements_Last__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements_Last__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The last recorded DML statements value.</description>
    <label>DML Statements Last</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker__c/fields/Heap_Alert_Change__c.field-meta.xml
<CustomField>
    <fullName>Heap_Alert_Change__c</fullName>
    <description>If the heap consumption increases by this percentage between snapshots raise an alert.</description>
    <label>Heap Alert Change</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker__c/fields/Heap_Alert_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Heap_Alert_Threshold_1__c</fullName>
    <description>Alert if the heap consumption exceeds this threshold</description>
    <label>Heap Alert Threshold 1</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker__c/fields/Heap_Last__c.field-meta.xml
<CustomField>
    <fullName>Heap_Last__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The last recorded heap value.</description>
    <label>Heap Last</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker__c/fields/Last_Snapshot__c.field-meta.xml
<CustomField>
    <fullName>Last_Snapshot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The last snapshot recorded for this limit tracker.</description>
    <label>Last Snapshot</label>
    <referenceTo>Limit_Tracker_Snapshot__c</referenceTo>
    <relationshipLabel>Limit Trackers</relationshipLabel>
    <relationshipName>Limit_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker__c/fields/SOQL_Queries_Last__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Queries_Last__c</fullName>
    <formula>Last_Snapshot__r.SOQL_Queries__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SOQL Queries Last</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Configuration__mdt/Limit_Tracker_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Configuration record for the limit tracker app.</description>
    <label>Limit Tracker Configuration</label>
    <pluralLabel>Limit Tracker Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Limit_Tracker_Configuration__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if limit consumption should be tracked.</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/Limit_Tracker_Snapshot__c.object-meta.xml
<CustomObject>
    <description>Snapshot of the limits consumption of a tracked piece of code.</description>
    <label>Limit Tracker Snapshot</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Limit Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limit Tracker Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>Contains additional information to help diagnose a sudden increase in limits consumption.</description>
    <label>Additional Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/CPU__c.field-meta.xml
<CustomField>
    <fullName>CPU__c</fullName>
    <description>The CPU time consumed by the tracked code (in milliseconds)</description>
    <label>CPU</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/CPU_Alert_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>CPU_Alert_Threshold_1__c</fullName>
    <formula>Limit_Tracker__r.CPU_Alert_Threshold_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CPU Alert Threshold 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/DML_Records__c.field-meta.xml
<CustomField>
    <fullName>DML_Records__c</fullName>
    <description>The number of DML records consumed by the tracked code.</description>
    <label>DML Records</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/DML_Statements__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements__c</fullName>
    <description>The number of DML statements consumed by the tracked code.</description>
    <label>DML Statements</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/Heap__c.field-meta.xml
<CustomField>
    <fullName>Heap__c</fullName>
    <description>The heap consumed by the tracked code in bytes.</description>
    <label>Heap</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/Heap_Alert_Threshold_1__c.field-meta.xml
<CustomField>
    <fullName>Heap_Alert_Threshold_1__c</fullName>
    <formula>Limit_Tracker__r.Heap_Alert_Threshold_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Heap Alert Threshold 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/Limit_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Limit_Tracker__c</fullName>
    <description>The parent limit tracker.</description>
    <label>Limit Tracker</label>
    <referenceTo>Limit_Tracker__c</referenceTo>
    <relationshipLabel>Limit Tracker Snapshots</relationshipLabel>
    <relationshipName>Limit_Tracker_Snapshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/SOQL_Queries__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Queries__c</fullName>
    <description>The number of SOQL queries consumed by the tracked code.</description>
    <label>SOQL Queries</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/SOQL_Records__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Records__c</fullName>
    <description>The number of SOQL records consumed by the tracked code.</description>
    <label>SOQL Records</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user executing the tracked code.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Limit_Tracker_Snapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LimitTrackerService.cls
public with sharing class LimitTrackerService 
{
    @TestVisible 
    private static LimitTrackerService instance;

    @TestVisible
    private Map<String, LimitSnapshot> trackersByName=new Map<String, LimitSnapshot>();

    @TestVisible
    public List<LimitSnapshot> snapshotsToPublish = new List<LimitSnapshot>();

    @TestVisible
    private Boolean trackingEnabled=false;

    private LimitTrackerService() 
    {

    }

    public static LimitTrackerService GetService()
    {
        if (null==instance)
        {
            instance=new LimitTrackerService();
            instance.getConfiguration();
        }

        return instance;
    }

    private void getConfiguration()
    {
        Limit_Tracker_Configuration__mdt config = 
                Limit_Tracker_Configuration__mdt.getInstance('Default');
    
        if (null!=config)
        {
            trackingEnabled=config.Enabled__c;
        }
    }

    public void startTracking(String name)
    {
        if (trackingEnabled)
        {
            LimitSnapshot snapshot=new LimitSnapshot(name);
            trackersByName.put(name, snapshot);
        }
    }

    public void startTracking(String name, String additionalInfo)
    {
        if (trackingEnabled)
        {
            LimitSnapshot snapshot=new LimitSnapshot(name, additionalInfo);
            trackersByName.put(name, snapshot);
        }
    }

    public LimitSnapshot stopTracking(String name)
    {
        LimitSnapshot snapshot=null;

        if (trackingEnabled)
        {
            LimitSnapshot start=trackersByName.remove(name);

            snapshot=new LimitSnapshot(name);

            snapshot.offsetFromStart(start);
        }

        return snapshot;
    }
    
    public Database.SaveResult stopTrackingAndPublishSnapshot(String name)
    {
        Database.SaveResult result=null;
        if (trackingEnabled)
        {        
            LimitSnapshot snapshot=stopTracking(name);

            result=this.publishSnapshot(snapshot);
        }

        return result;
    }
    
    public void stopTrackingAndQueueSnapshot(String name)
    {
        if (trackingEnabled)
        {
            LimitSnapshot snapshot=stopTracking(name);

            snapshotsToPublish.add(snapshot);
        }
    }

    public List<Database.SaveResult> publishQueuedSnapshots()
    {
        List<Database.SaveResult> results=null;

        if (trackingEnabled)
        {
            if (!snapshotsToPublish.isEmpty())
            {
                results=publishSnapshots(snapshotsToPublish);
            }
        }

        return results;
    }

    private Database.SaveResult publishSnapshot(LimitSnapshot snapshot)
    {
        Database.SaveResult result=null;

        if (trackingEnabled)
        {
            List<Database.SaveResult> results=publishSnapshots(new List<LimitSnapshot>{snapshot});

            result=results[0];
        }

        return result;
    }

    private List<Database.SaveResult> publishSnapshots(List<LimitSnapshot> snapshots) 
    {
        List<Limit_Snapshot__e> lsEvents=new List<Limit_Snapshot__e>();
        for (LimitSnapshot snapshot : snapshots)
        {
            Limit_Snapshot__e lsEvent=snapshot.toSnapshotEvent();
            lsEvents.add(lsEvent);
        }

        List<Database.SaveResult> results = EventBus.publish(lsEvents);

        // Inspect publishing result for each event
        for (Database.SaveResult sr : results) {
            if (sr.isSuccess()) 
            {
                System.debug('Successfully published event.');
            } 
            else 
            {
                for(Database.Error err : sr.getErrors()) 
                {
                    System.debug('Error returned: ' +
                                err.getStatusCode() +
                                ' - ' +
                                err.getMessage());
                }
            }       
        }

        return results;
    }

    public void processSnapshotEvents(List<Limit_Snapshot__e> snapshots)
    {
        if (trackingEnabled)
        {
            Map<String, List<Limit_Snapshot__e>> snapshotsByName=
                            new Map<String, List<Limit_Snapshot__e>>();

            for (Limit_Snapshot__e snapshot : snapshots)
            {
                List<Limit_Snapshot__e> snapshotsForName=
                        snapshotsByName.get(snapshot.Name__c);

                if (null==snapshotsForName)
                {
                    snapshotsForName=new List<Limit_Snapshot__e>();
                    System.debug('Name = ' + snapshot.Name__c);
                    snapshotsByName.put(snapshot.Name__c, snapshotsForName);
                }

                snapshotsForName.add(snapshot);
            }

            Map<Id, Limit_Tracker__c> limitTrackersById=new Map<Id, Limit_Tracker__c>(
                        [select Id, Name
                         from Limit_Tracker__c 
                         where Name in :snapshotsByName.keySet()]);

            List<Limit_Tracker_Snapshot__c> trackerSnapshotsToAdd=
                        new List<Limit_Tracker_Snapshot__c>();

            Map<Id, Limit_Tracker_Snapshot__c> lastSnapshotForTracker=new Map<Id, Limit_Tracker_Snapshot__c>();

            for (Limit_Tracker__c tracker : limitTrackersById.values())
            {
                DateTime lastDT=null;

                List<Limit_Snapshot__e> snapshotsForTracker=
                        snapshotsByName.get(tracker.Name);

                for (Limit_Snapshot__e snapshot : snapshotsForTracker)
                {
                    Limit_Tracker_Snapshot__c trackerSnapshot=
                                        new Limit_Tracker_Snapshot__c();

                    trackerSnapshot.CPU__c=snapshot.CPU__c;
                    trackerSnapshot.DML_Records__c=snapshot.DML_Records__c;
                    trackerSnapshot.DML_Statements__c=snapshot.DML_Statements__c;
                    trackerSnapshot.Heap__c=snapshot.Heap__c;
                    trackerSnapshot.SOQL_Queries__c=snapshot.SOQL_Queries__c;
                    trackerSnapshot.SOQL_Records__c=snapshot.SOQL_Records__c;
                    trackerSnapshot.Additional_Information__c=snapshot.Additional_Information__c;
                    trackerSnapshot.Limit_tracker__c=tracker.Id;    
                    trackerSnapshot.User__c=snapshot.User_Id__c;
                    trackerSnapshotsToAdd.add(trackerSnapshot);

                    if ( (null==lastDT) || (snapshot.CreatedDate > lastDT) )
                    {
                        lastDT=snapshot.CreatedDate;
                        tracker.CPU_Last__c=snapshot.CPU__c;
                        tracker.Heap_Last__c=snapshot.Heap__c;  
                        tracker.DML_Records_Last__c=snapshot.DML_Records__c;    
                        tracker.DML_Statements_Last__c=snapshot.DML_Statements__c;  
                        tracker.SOQL_Queries_Last__c=snapshot.SOQL_Queries__c;  
                        lastSnapshotForTracker.put(tracker.Id, trackerSnapshot);
                    }
                }
            }

            insert trackerSnapshotsToAdd;
            for (Id trackerId : lastSnapshotForTracker.keySet())
            {
                System.debug('Setting limit tracker ' + limitTrackersById.get(trackerId).Name + ' last to ' + lastSnapshotForTracker.get(trackerId).Id);
                limitTrackersById.get(trackerId).Last_Snapshot__c=lastSnapshotForTracker.get(trackerId).Id;
            }
            update limitTrackersById.values();
        }
    }

    public void processUpdates(List<Limit_Tracker__c> oldTrackers, 
                                List<Limit_Tracker__c> newTrackers)
    {
        if (trackingEnabled)
        {
            List<Id> snapshotIds=new List<Id>();
            for (Limit_Tracker__c tracker : newTrackers)
            {
                snapshotIds.add(tracker.Last_Snapshot__c);   
            }
            Map<Id, Limit_Tracker_Snapshot__c> snapshotsById=
                           new Map<Id, Limit_Tracker_Snapshot__c>([select Id, Additional_Information__c 
                                               from Limit_Tracker_Snapshot__c where Id in :snapshotIds]);
                                               
            List<LimitTrackerAlert> alerts=new List<LimitTrackerAlert>();

            System.debug('Processing tracker updates');
            for (Integer idx=0; idx<oldTrackers.size(); idx++)
            {
                Limit_Tracker__c oldTracker=oldTrackers[idx];
                Limit_Tracker__c newTracker=newTrackers[idx];

                alerts.addAll(raiseAlerts(newTracker, snapshotsById.get(newTracker.Last_Snapshot__c), 
                                'Heap', oldTracker.Heap_Last__c.intValue(), 
                            newTracker.Heap_Last__c.intValue(),
                            newTracker.Heap_Alert_Threshold_1__c?.intValue(),
                            newTracker.Heap_Alert_Change__c?.intValue()));
                
                alerts.addAll(raiseAlerts(newTracker, snapshotsById.get(newTracker.Last_Snapshot__c), 
                            'CPU', oldTracker.CPU_Last__c.intValue(), 
                            newTracker.CPU_Last__c.intValue(),
                            newTracker.CPU_Alert_Threshold_1__c?.intValue(),
                            newTracker.CPU_Alert_Change__c?.intValue()));
            }

            if (!alerts.isEmpty())
            {
                sendAlerts(alerts);
            }
        }
    }

    private List<LimitTrackerAlert> raiseAlerts(Limit_Tracker__c tracker, Limit_Tracker_Snapshot__c last, 
                                                String which, 
                                                Integer oldVal, Integer newVal,
                                                Integer alertThreshold, Integer changePercent)
    {
        List<LimitTrackerAlert> alerts=new List<LimitTrackerAlert>();

        System.debug('Old ' + which + ' = ' + oldVal);
        System.debug('New ' + which + ' = ' + newVal);

        if (oldVal<newVal)
        {
            System.debug(which + ' increased');
            if ( (null!=alertThreshold) && (newVal>alertThreshold) )
            {
                alerts.add(new LimitTrackerAlert(tracker.Name + ' ' + which + ' limit consumption alert',
                              'The ' + which + ' limit consumption alert threshold of ' + alertThreshold + 
                              ' has been exceeded with a value of ' + newVal + 
                              '<p>Additional information:</p>' + 
                              '<p>' + last.Additional_Information__c + '</p>')); 
                System.debug(which + ' alert threshold 1 exceeded');
            }
                
            // don't alert for the first record
            if ( (null!=changePercent) && (0!=oldVal) )
            {
                Integer diff=newVal-oldVal;
                Integer percent=(diff * 100) / oldVal;
                System.debug('Percent = ' + percent + ' and threshold = ' + changePercent);
                if (percent>=changePercent)
                {
                    alerts.add(new LimitTrackerAlert(tracker.Name + ' ' + which + ' limit consumption alert',
                              'The ' + which + ' limit consumption percentage change of ' + newVal + 
                                ' exceeded the configured value of ' + changePercent + 
                                '<p>Additional information:</p>' + 
                                '<p>' + last.Additional_Information__c + '</p>')); 

                    System.debug(which + ' percentage change exceeded');
                }                    
            }
        }

        return alerts;
    }

    public void sendAlerts(List<LimitTrackerAlert> alerts)
    {
        System.debug('Alerts = ' + alerts);
        List<LimitNotifierInterface> notifiers=new List<LimitNotifierInterface>();

        List<Limit_Alert_Notifier__mdt> notifierMDTs=Limit_Alert_Notifier__mdt.getAll().values();
        for (Limit_Alert_Notifier__mdt notifierMDT : notifierMDTs)
        {
            System.Type notType=Type.forName(notifierMDT.Namespace__c,
                                            notifierMDT.Apex_Class__c);

            LimitNotifierInterface notifier=(LimitNotifierInterface) notType.newInstance();
                                                  

            notifier.configure(notifierMDT.Additional_Config__c);
            notifiers.add(notifier);
        }

        for (LimitNotifierInterface notifier : notifiers)
        {
            notifier.notify(alerts);
        }
    }
}