force-app/main/default/objects/Limit_Tracker_Snapshot__c/Limit_Tracker_Snapshot__c.object-meta.xml
<CustomObject>
    <description>Snapshot of the limits consumption of a tracked piece of code.</description>
    <label>Limit Tracker Snapshot</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Limit Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limit Tracker Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>Contains additional information to help diagnose a sudden increase in limits consumption.</description>
    <label>Additional Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user executing the tracked code.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Limit_Tracker_Snapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LimitSnapshotDAO.cls
public with sharing class LimitSnapshotDAO {
    public LimitSnapshotDAO() {
    }

    public Map<Id, sObject> getRelatedRecords(Set<Id> relatedRecordIds) {
        Map<String, Set<Id>> relatedRecordIdsByObjectName=new Map<String, Set<Id>>();
        for (Id relatedId : relatedRecordIds) {
            Schema.SObjectType sobType = relatedId.getSObjectType();
            if (sobType != null) {
                String objectName = sobType.getDescribe().getName();
                Set<Id> ids = relatedRecordIdsByObjectName.get(objectName);
                if (ids == null) {
                    ids = new Set<Id>();
                    relatedRecordIdsByObjectName.put(objectName, ids);
                }
                ids.add(relatedId);
            }
        }

        Map<Id, sObject> sobjectsById=new Map<Id, sObject>();
        for (String objectName : relatedRecordIdsByObjectName.keySet()) {
            Set<Id> relatedRecordIdsForObjectName = relatedRecordIdsByObjectName.get(objectName);
            String query = 'SELECT Id, Name, LastModifiedDate FROM ' + objectName + ' WHERE Id IN :relatedRecordIdsForObjectName';
            List<sObject> sobjectsFromDB=Database.query(query);
            for (sObject sobjectFromDB : sobjectsFromDB) {
                sobjectsById.put(sobjectFromDB.Id, sobjectFromDB);
            }
        }

        return sobjectsById;
    }

    public Limit_Tracker_Snapshot__c getLimitSnapshot(Id recordId) {
        return [select Id, User__c, Additional_Information__c, LastModifiedDate from Limit_Tracker_Snapshot__c where Id=:recordId];
    }
}