force-app/main/default/objects/Limit_Tracker_Snapshot__c/Limit_Tracker_Snapshot__c.object-meta.xml
<CustomObject>
    <description>Snapshot of the limits consumption of a tracked piece of code.</description>
    <label>Limit Tracker Snapshot</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Limit Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limit Tracker Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <description>Contains additional information to help diagnose a sudden increase in limits consumption.</description>
    <label>Additional Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user executing the tracked code.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Limit_Tracker_Snapshots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LimitSnapshotService.cls
public with sharing class LimitSnapshotService implements LimitSnapshotServiceIF {
    @TestVisible 
    private static LimitSnapshotServiceIF instance;

    @TestVisible
    private LimitSnapshotDAO dao=new LimitSnapshotDAO();

    private LimitSnapshotService() 
    {
    }

    public static LimitSnapshotServiceIF GetService()
    {
        if (null==instance)
        {
            instance=new LimitSnapshotService();
        }

        return instance;
    }

    public List<AssociatedRecord> getAssociatedRecordsForSnapshot(Id limitSnapshotId) {
        Map<Id, String> labelsByRecordId=new Map<Id, String>();

        Limit_Tracker_Snapshot__c snapshot=dao.getLimitSnapshot(limitSnapshotId);
        labelsByRecordId.put(snapshot.User__c, 'Running User');
        Map<String, Object> propsByName = 
                    (Map<String, Object>) JSON.deserializeUntyped(snapshot.Additional_Information__c);

        for (String propName: propsByName.keySet()) {
            System.debug('Handling property ' + propName);
            Map<String, Object> propValue = (Map<String, Object>) propsByName.get(propName);            
            if (propValue.containsKey('recordId')) {
                Id recordId = (Id) propValue.get('recordId');
                labelsByRecordId.put(recordId, propName);
            }
        }

        Map<Id, sObject> recordsById=dao.getRelatedRecords(labelsByRecordId.keySet());

        List<AssociatedRecord> associatedRecords=new List<AssociatedRecord>();
        
        for (Id recordId : labelsByRecordId.keySet()) {
            String label=labelsByRecordId.get(recordId);
            sObject record=recordsById.get(recordId);
            String message;
            if (null==record) {
                message='Record not found - has it been deleted?';
            }
            else if ((DateTime) (record.get('LastModifiedDate'))>snapshot.LastModifiedDate) {
                message='Record has been updated since snapshot was taken';
            }
            System.debug('Label = ' + label);
            System.debug('Last modified = ' + (DateTime) (record.get('LastModifiedDate')));
            System.debug('Snapshot date = ' + snapshot.LastModifiedDate);
            associatedRecords.add(new AssociatedRecord(label, recordsById.get(recordId),
                                                        message));
        }

        return associatedRecords;
    }
}