force-app/main/default/objects/Limit_Snapshot__e/Limit_Snapshot__e.object-meta.xml
<CustomObject>
    <description>Snapshot of key limit consumption by a discrete piece of code.</description>
    <label>Limit Snapshot</label>
    <pluralLabel>Limit Snapshots</pluralLabel>
</CustomObject>

force-app/main/default/objects/Limit_Tracker__c/Limit_Tracker__c.object-meta.xml
<CustomObject>
    <description>Object to track limit consumption of a discrete piece of code.</description>
    <label>Limit Tracker</label>
    <nameField>
        <label>Limit Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Limit Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/Limit_Tracker_Snapshot__c.object-meta.xml
<CustomObject>
    <description>Snapshot of the limits consumption of a tracked piece of code.</description>
    <label>Limit Tracker Snapshot</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Limit Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limit Tracker Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/Limit_Tracker__c.field-meta.xml
<CustomField>
    <fullName>Limit_Tracker__c</fullName>
    <description>The parent limit tracker.</description>
    <label>Limit Tracker</label>
    <referenceTo>Limit_Tracker__c</referenceTo>
    <relationshipLabel>Limit Tracker Snapshots</relationshipLabel>
    <relationshipName>Limit_Tracker_Snapshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LimitTrackerServiceIF.cls
public interface LimitTrackerServiceIF {
    void enableTracking(Boolean enabled);
    void startTracking(String name);
    void startTracking(String name, String additionalInfo);
    LimitSnapshot stopTracking(String name);
    Database.SaveResult stopTrackingAndPublishSnapshot(String name);    
    void stopTrackingAndQueueSnapshot(String name);
    List<Database.SaveResult> publishQueuedSnapshots();
    void processSnapshotEvents(List<Limit_Snapshot__e> snapshots);
    void processUpdates(List<Limit_Tracker__c> oldTrackers, 
                             List<Limit_Tracker__c> newTrackers);
    void processTrackerSnapshots(List<Limit_Tracker_Snapshot__c> snapshots);
}