force-app/main/default/objects/Limit_Snapshot__e/Limit_Snapshot__e.object-meta.xml
<CustomObject>
    <description>Snapshot of key limit consumption by a discrete piece of code.</description>
    <label>Limit Snapshot</label>
    <pluralLabel>Limit Snapshots</pluralLabel>
</CustomObject>

force-app/main/default/objects/Limit_Snapshot__e/fields/CPU__c.field-meta.xml
<CustomField>
    <fullName>CPU__c</fullName>
    <description>The CPU consumed by the tracked code (in milliseconds)</description>
    <label>CPU</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/DML_Records__c.field-meta.xml
<CustomField>
    <fullName>DML_Records__c</fullName>
    <description>The number of DML records consumed by the tracked code.</description>
    <label>DML Records</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/DML_Statements__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements__c</fullName>
    <description>The number of DML statements consumed by the tracked code.</description>
    <label>DML Statements</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/Heap__c.field-meta.xml
<CustomField>
    <fullName>Heap__c</fullName>
    <description>The heap consumed by the tracked code in bytes.</description>
    <label>Heap</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>The unique name for the discrete piece of code for which limit consumption is captured - this does not need to be a method or class name, just the name that you refer to for that processing.</description>
    <label>Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/SOQL_Queries__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Queries__c</fullName>
    <description>The number of SOQL queries consumed by the tracked code.</description>
    <label>SOQL Queries</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Snapshot__e/fields/SOQL_Records__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Records__c</fullName>
    <description>The number of SOQL records consumed by the tracked code.</description>
    <label>SOQL Records</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/Limit_Tracker_Snapshot__c.object-meta.xml
<CustomObject>
    <description>Snapshot of the limits consumption of a tracked piece of code.</description>
    <label>Limit Tracker Snapshot</label>
    <nameField>
        <displayFormat>LS-{000000}</displayFormat>
        <label>Limit Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Limit Tracker Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/CPU__c.field-meta.xml
<CustomField>
    <fullName>CPU__c</fullName>
    <description>The CPU time consumed by the tracked code (in milliseconds)</description>
    <label>CPU</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/DML_Records__c.field-meta.xml
<CustomField>
    <fullName>DML_Records__c</fullName>
    <description>The number of DML records consumed by the tracked code.</description>
    <label>DML Records</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/DML_Statements__c.field-meta.xml
<CustomField>
    <fullName>DML_Statements__c</fullName>
    <description>The number of DML statements consumed by the tracked code.</description>
    <label>DML Statements</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/Heap__c.field-meta.xml
<CustomField>
    <fullName>Heap__c</fullName>
    <description>The heap consumed by the tracked code in bytes.</description>
    <label>Heap</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/SOQL_Queries__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Queries__c</fullName>
    <description>The number of SOQL queries consumed by the tracked code.</description>
    <label>SOQL Queries</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Limit_Tracker_Snapshot__c/fields/SOQL_Records__c.field-meta.xml
<CustomField>
    <fullName>SOQL_Records__c</fullName>
    <description>The number of SOQL records consumed by the tracked code.</description>
    <label>SOQL Records</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LimitSnapshot.cls
public with sharing class LimitSnapshot 
{
    public String name;
    public Integer cpu;
    public Integer heap;
    public Integer dmlRecords;
    public Integer dmlStatements;
    public Integer soqlQueries;
    public Integer soqlRecords;

    public LimitSnapshot(String name)
    {
        this.name=name;
        this.cpu=Limits.getCpuTime();
        this.heap=Limits.getHeapSize();
        this.dmlRecords=Limits.getDmlRows();
        this.dmlStatements=Limits.getDmlStatements();
        this.soqlQueries=Limits.getQueries();
        this.soqlRecords=Limits.getQueryRows();
    }

    public void offsetFromStart(LimitSnapshot start)
    {
        // if start is null, we'll assume it is for the entirety
        // of the transaction.
        if (null!=start)
        {
            this.cpu-=start.cpu;
            this.heap-=start.heap;
            this.dmlRecords-=start.dmlRecords;
            this.dmlStatements-=start.dmlStatements;
            this.soqlQueries-=start.soqlQueries;
            this.soqlRecords-=start.soqlRecords;
        }
    }

    public LimitSnapshot(Limit_Tracker_Snapshot__c snapshot)
    {
        this.name=snapshot.Name;
        this.cpu=snapshot.CPU__c.intValue();
        this.heap=snapshot.Heap__c.intValue();
        this.dmlRecords=snapshot.DML_Records__c.intValue();
        this.dmlStatements=snapshot.DML_Statements__c.intValue();
        this.soqlQueries=snapshot.SOQL_Queries__c.intValue();
        this.soqlRecords=snapshot.SOQL_Records__c.intValue();
    }

    public LimitSnapshot(Limit_Snapshot__e snapshot)
    {
        this.name=snapshot.Name__c;
        this.cpu=snapshot.CPU__c.intValue();
        this.heap=snapshot.Heap__c.intValue();
        this.dmlRecords=snapshot.DML_Records__c.intValue();
        this.dmlStatements=snapshot.DML_Statements__c.intValue();
        this.soqlQueries=snapshot.SOQL_Queries__c.intValue();
        this.soqlRecords=snapshot.SOQL_Records__c.intValue();
    }

    public Limit_Snapshot__e toSnapshotEvent()
    {
        Limit_Snapshot__e snEv=new Limit_Snapshot__e(Name__c=this.name,
                                                     CPU__c=this.cpu,
                                                     Heap__c=this.heap,
                                                     DML_Records__c=this.dmlRecords,
                                                     DML_Statements__c=this.dmlStatements,
                                                     SOQL_Queries__c=this.soqlQueries,
                                                     SOQL_Records__c=this.soqlRecords);
        return snEv;
    }        
}